# Generated by Django 3.0.5 on 2020-05-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pydate', '0002_remove_userdata_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='nick',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='personality',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sex',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
