# Generated by Django 3.0.5 on 2020-05-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pydate', '0003_auto_20200509_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='location',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
