# Generated by Django 3.0.5 on 2020-05-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pydate', '0005_auto_20200509_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='nick',
            new_name='username',
        ),
    ]
