# Generated by Django 3.0.5 on 2020-05-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pydate', '0007_auto_20200509_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='searching_for',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
