# Generated by Django 3.0.5 on 2020-05-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pydate', '0008_userdata_searching_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='username',
        ),
    ]
