# Generated by Django 3.0.5 on 2020-05-13 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pydate', '0009_auto_20200513_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='instagram',
        ),
    ]
