# Generated by Django 3.0.5 on 2020-05-14 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pydate', '0010_auto_20200513_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalquestionuser',
            name='user',
        ),
        migrations.AddField(
            model_name='personalquestionuser',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
