# Generated by Django 3.0.5 on 2020-05-23 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pydate', '0013_auto_20200514_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='photo',
            field=models.ImageField(null=True, upload_to='user_profile_pictures/'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_questions_match', models.CharField(choices=[('00', 'Agree None'), ('01', 'Agree 1 To 2'), ('10', 'Agree 2 To 1'), ('11', 'Agree Both')], default='00', max_length=2)),
                ('chatting_match', models.CharField(choices=[('00', 'Agree None'), ('01', 'Agree 1 To 2'), ('10', 'Agree 2 To 1'), ('11', 'Agree Both')], default='00', max_length=2)),
                ('user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
