# Generated by Django 3.0.6 on 2020-06-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pydate', '0014_auto_20200523_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='location',
        ),
        migrations.AddField(
            model_name='userdata',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/user_profile_pictures/'),
        ),
    ]
