# Generated by Django 3.0.5 on 2020-05-30 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pydate', '0014_auto_20200523_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityTestItem',
            fields=[
                ('itemID', models.IntegerField(primary_key=True, serialize=False)),
                ('first_option', models.CharField(max_length=250)),
                ('second_option', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('IE', 'TypeIE'), ('SN', 'TypeSN'), ('FT', 'TypeFT'), ('JP', 'TypeJP')], max_length=2)),
                ('inversion', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterField(
            model_name='userdata',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/user_profile_pictures/'),
        ),
        migrations.CreateModel(
            name='PersonalityTestAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(null=True)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pydate.PersonalityTestItem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
