# Generated by Django 3.0.6 on 2020-06-04 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pydate', '0014_auto_20200523_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='location',
        ),
        migrations.AddField(
            model_name='userdata',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/user_profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
