# Generated by Django 3.0.5 on 2020-05-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pydate', '0015_auto_20200530_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='personality',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
